### ISSUE TITLE
Not working with ReactNative 0.71.3

### ISSUE THREAD

**Issue by Yannick-Bruening** [invertase/react-native-gradle-plugin#11]
Hi, im trying to get this to work with react-native 0.71.3.

But It looks like they've changed `com.facebook.react-native` to `com.facebook.react-android`.
And some other smaller changes.

Are there any plans to support this in the near future? I really need this for our app :)

**Comment by mikehardy** [comment]
Interesting - this is something that will obviously be interesting to us over at react-native-firebase (where we use this plugin, naturally) I just haven't had time to update our e2e test app to 0.71+  so I didn't even realize this would be a problem.

Makes sense though, they did need to change their coordinates, that was fun with all the build breaks as they published on the old coordinates once to maven central.

What have you tried so far? What errors do you see currently?

**Comment by Yannick-Bruening** [comment]
Hi, it seems like my issue was caused by some weird gradle caching that broke the `com.facebook.react:react-native:+` import.

After clearing the gradle cache this issue has resolved itself.

Thanks for your help anyways :)

**Comment by mikehardy** [comment]
Ha - one less thing potentially on my plate, I love it! Caches ... so useful ... cache coherency ... so hard. Cheers
