### ISSUE TITLE
./gradlew clean is failing. Plugin [id: 'io.invertase.gradle.build', version: '1.4'] was not found

### ISSUE THREAD

**Issue by rt9092** [invertase/react-native-gradle-plugin#4]
* Where:
Build file '/Users/romiltiwari/Documents/FreightTiger/optimus/node_modules/@react-native-firebase/analytics/android/build.gradle' line: 20

* What went wrong:
Plugin [id: 'io.invertase.gradle.build', version: '1.4'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.invertase.gradle.build:io.invertase.gradle.build.gradle.plugin:1.4')
  Searched in the following repositories:
    Gradle Central Plugin Repository

PS - This same plugin version is used across all React Native Firebase modules my project is using.
        "@react-native-firebase/analytics": "7.6.7",
        "@react-native-firebase/app": "8.4.5",
        "@react-native-firebase/crashlytics": "8.4.8",
        "@react-native-firebase/dynamic-links": "7.5.9",
        "@react-native-firebase/messaging": "7.9.0",

**Comment by mikehardy** [comment]
Hi there! Related perhaps to https://github.com/invertase/react-native-firebase/issues/4444 (though that is windows 10)

Users reported success with gradle downgrades, but based on the reports there I think there is actually some sort of gradle daemon / caching mis-behavior

I am completely unable to reproduce this problem and I build from scratch on macOS all the time - with this as a test harness: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by rt9092** [comment]
@mikehardy Clearing all cache worked for me. Thanks
