### ISSUE TITLE
SchemaJsonParser.java使用或覆盖了已过时的 API。

### ISSUE THREAD

**Issue by chaifuling** [invertase/react-native-gradle-plugin#6]
diff --git a/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/JavaGenerator.class b/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/JavaGenerator.class
new file mode 100644
index 0000000..bb1e0cd
Binary files /dev/null and b/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/JavaGenerator.class differ
diff --git a/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/SchemaJsonParser.class b/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/SchemaJsonParser.class
new file mode 100644
index 0000000..1682df0
Binary files /dev/null and b/node_modules/react-native-gradle-plugin/bin/main/com/facebook/react/codegen/generator/SchemaJsonParser.class differ
diff --git a/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java b/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java
index d4848d1..a14bf49 100644
--- a/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java
+++ b/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java
@@ -53,8 +53,8 @@ public final class SchemaJsonParser {
 
   private TypeData buildTypeData(final File schemaFile)
       throws CodegenException, FileNotFoundException, IOException {
-    final JsonParser parser = new JsonParser();
-    final JsonElement rootElement = parser.parse(new FileReader(schemaFile));
+    // final JsonParser parser = new JsonParser();
+    final JsonElement rootElement = JsonParser.parseReader(new FileReader(schemaFile));
 
     final Map<String, Map<String, NativeModuleType>> collection = new HashMap<>();
 
@@ -83,12 +83,11 @@ public final class SchemaJsonParser {
                   }
                 }
 
-                final Type parsedType =
-                    parseNativeModule(
-                        // TODO (T71955395): NativeModule spec type name does not
-                        // exist in the schema. For now assume it's "Spec".
-                        // The final type name will be the output class name.
-                        TypeId.of(jsModuleName, jsModuleName + "Spec"), jsModule);
+                final Type parsedType = parseNativeModule(
+                    // TODO (T71955395): NativeModule spec type name does not
+                    // exist in the schema. For now assume it's "Spec".
+                    // The final type name will be the output class name.
+                    TypeId.of(jsModuleName, jsModuleName + "Spec"), jsModule);
                 mTypeData.addType(parsedType);
               });
     }
@@ -168,29 +167,27 @@ public final class SchemaJsonParser {
     final JsonObject aliases = json.getAsJsonObject("aliases");
     final JsonArray properties = json.getAsJsonObject("spec").getAsJsonArray("properties");
 
-    final ImmutableList<Type> collectedAliases =
-        ImmutableList.copyOf(
-            aliases.entrySet().stream()
-                .map(
-                    entry -> {
-                      final String typeName = entry.getKey();
-                      final JsonObject typeAnnotation = entry.getValue().getAsJsonObject();
-                      // The alias name is the type name that other types can refer to.
-                      return parseTypeAnnotation(
-                          TypeId.of(typeId.moduleName, typeName), typeAnnotation);
-                    })
-                .collect(Collectors.toList()));
+    final ImmutableList<Type> collectedAliases = ImmutableList.copyOf(
+        aliases.entrySet().stream()
+            .map(
+                entry -> {
+                  final String typeName = entry.getKey();
+                  final JsonObject typeAnnotation = entry.getValue().getAsJsonObject();
+                  // The alias name is the type name that other types can refer to.
+                  return parseTypeAnnotation(
+                      TypeId.of(typeId.moduleName, typeName), typeAnnotation);
+                })
+            .collect(Collectors.toList()));
 
-    ImmutableList.Builder<NativeModuleType.Property> collectedPropertiesBuilder =
-        new ImmutableList.Builder<>();
+    ImmutableList.Builder<NativeModuleType.Property> collectedPropertiesBuilder = new ImmutableList.Builder<>();
     properties.forEach(
         p -> {
           final JsonObject node = p.getAsJsonObject();
           final String name = node.get("name").getAsString();
           final JsonObject typeAnnotation = node.getAsJsonObject("typeAnnotation");
           final boolean optional = node.get("optional").getAsBoolean();
-          final TypeId propertyTypeId =
-              TypeId.expandOf(typeId, CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_CAMEL, name));
+          final TypeId propertyTypeId = TypeId.expandOf(typeId,
+              CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_CAMEL, name));
           collectedPropertiesBuilder.add(
               new NativeModuleType.Property(
                   name, parseTypeAnnotation(propertyTypeId, typeAnnotation), optional));
@@ -209,10 +206,9 @@ public final class SchemaJsonParser {
     final JsonObject elementTypeAnnotation = typeAnnotation.getAsJsonObject("elementType");
     final TypeId elementTypeId = TypeId.expandOf(typeId, "ElementType");
     // TODO (T71847026): Some array types are missing elementType annotation.
-    final Type elementType =
-        elementTypeAnnotation != null
-            ? parseTypeAnnotation(elementTypeId, elementTypeAnnotation)
-            : new AnyType(elementTypeId);
+    final Type elementType = elementTypeAnnotation != null
+        ? parseTypeAnnotation(elementTypeId, elementTypeAnnotation)
+        : new AnyType(elementTypeId);
     return new ArrayType(typeId, elementType);
   }
 
@@ -234,8 +230,7 @@ public final class SchemaJsonParser {
     }
 
     final JsonObject returnTypeAnnotation = typeAnnotation.getAsJsonObject("returnTypeAnnotation");
-    final Type returnType =
-        parseTypeAnnotation(TypeId.expandOf(typeId, "ReturnType"), returnTypeAnnotation);
+    final Type returnType = parseTypeAnnotation(TypeId.expandOf(typeId, "ReturnType"), returnTypeAnnotation);
 
     return new FunctionType(typeId, paramsList.build(), returnType);
   }
@@ -250,8 +245,8 @@ public final class SchemaJsonParser {
           final String name = node.get("name").getAsString();
           final boolean optional = node.get("optional").getAsBoolean();
           final JsonObject propertyTypeAnnotation = node.getAsJsonObject("typeAnnotation");
-          final TypeId propertyTypeId =
-              TypeId.expandOf(typeId, CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_CAMEL, name));
+          final TypeId propertyTypeId = TypeId.expandOf(typeId,
+              CaseFormat.LOWER_CAMEL.to(CaseFormat.UPPER_CAMEL, name));
           final Type propertyType = parseTypeAnnotation(propertyTypeId, propertyTypeAnnotation);
           propertiesList.add(new ObjectType.Property(name, propertyType, optional));
         });

Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
注: /Users/caifuling/git/移动端app框架/tsApp/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/caifuling/git/移动端app框架/tsApp/android/build.gradle' line: 57

**Comment by mikehardy** [comment]
I'm sorry, I can't read this because of the formatting, and you have not explained what your problem is in any way I understand.

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/mcve

If you'd like to open a new issue following the general ideas in those two links, we could investigate
