### ISSUE TITLE
This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)

### ISSUE THREAD

**Issue by hugoh59** [invertase/react-native-gradle-plugin#7]
After upgrading to RN 0.70.6 I keep getting this issue on android, haven't found a solution for days. 
````
> Task :react-native-gradle-plugin:compileKotlin FAILED
e: /Users/hugohouyez/code/hugoh1995/Superprof/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt: (137, 11): This declaration is experimental and its usage must be marked with '@kotlin.ExperimentalStdlibApi' or '@OptIn(kotlin.ExperimentalStdlibApi::class)'
````

**Comment by mikehardy** [comment]
> /react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt

While named similarly, this is a different plugin. You want:

https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt
