### ISSUE TITLE
  > Could not resolve all task dependencies for configuration ':classpath'.       > Could not find com.android.tools.build:gradle:7.2.1.

### ISSUE THREAD

**Issue by mohammad6vakili** [invertase/react-native-gradle-plugin#8]

**Comment by mohammad6vakili** [comment]
Hi I created a new react native app using react native cli `npx react-native init testApp`.
But I faced this issue.

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'hello'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools.build:gradle:7.2.1.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/7.2.1/gradle-7.2.1.pom
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.2.1/gradle-7.2.1.pom
        Required by:
            project :
            project : > project :react-native-gradle-plugin

can you help me please?
@Salakar @mikehardy

**Comment by mikehardy** [comment]
Wrong repo
